[package]
name = "logmaster_batch_downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.8", features= ["cookies", "gzip"]}
scraper = "0.20.0"
tokio = { version = "1.40.0", features = ["full"] }
chrono = "0.4.38"
